// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoPcThDXNrevp6wVtgl94NVTB4kWm__58',
    appId: '1:75952105530:web:788c2b8e31bc7236606d03',
    messagingSenderId: '75952105530',
    projectId: 'todo-c21de',
    authDomain: 'todo-c21de.firebaseapp.com',
    storageBucket: 'todo-c21de.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsrSkXLuHiIYJrUAYYsautkQ3f2VEnN-g',
    appId: '1:75952105530:android:4d197171a149958c606d03',
    messagingSenderId: '75952105530',
    projectId: 'todo-c21de',
    storageBucket: 'todo-c21de.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_dzqrUb-qi-Gh5vRn3uXXCelsWdWe7V4',
    appId: '1:75952105530:ios:dcde49d7c1ee2946606d03',
    messagingSenderId: '75952105530',
    projectId: 'todo-c21de',
    storageBucket: 'todo-c21de.appspot.com',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_dzqrUb-qi-Gh5vRn3uXXCelsWdWe7V4',
    appId: '1:75952105530:ios:4f794e8b021ef0ab606d03',
    messagingSenderId: '75952105530',
    projectId: 'todo-c21de',
    storageBucket: 'todo-c21de.appspot.com',
    iosBundleId: 'com.example.todo.RunnerTests',
  );
}
